# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Chace
email: alex@frenziedstasis.org
description: >- # this means to ignore newlines until "baseurl:"
  Ph.D. student in Moving Image Studies at Georgia State University.
footer: Alex Chace.

baseurl: "/jekyll-cv" # the subpath of your site, e.g. /blog
url: "http://alexchace.com" # the base hostname & protocol for your site, e.g. http://example.com

bio: >-
  I am an interdisciplinary scholar with interests in anarchism, cybernetics, queer/trans studies, horror films, psychoanalysis, and posthumanism.
pronouns: they/them/theirs

twitter: alreadyseveral
github:  leximch
linkedin: leximch
blog: frenziedstasis.org
gtag: UA-121343197-1

permalink: /:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-scholar


scholar:
  last_name: Chace

  style: modern-language-association
  
  locale: en
  
  sort_by: year,date
  
  order: descending
  bibliography_template: new_bib

  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details